#!/usr/local/bin/perl -wT
use strict;
use lib "lib";
use Bio::DasLite;
use Data::Dumper;

my $counts = {};
my $cb = sub {
  my $struct = shift;
  $counts->{$struct->{'dsn'}}++;
  print STDERR Dumper($struct);
};

my $das = Bio::DasLite->new({
			     'timeout'  => 30,
			     'dsn'      => [qw(
					     http://das.ensembl.org/das/hydraeuf_00000281
					     http://das.ensembl.org/das/hydraeuf_00000282
					     http://das.ensembl.org/das/hydraeuf_00000283
					     http://das.ensembl.org/das/hydraeuf_00000284
					     http://das.ensembl.org/das/hydraeuf_00000285
					     http://das.ensembl.org/das/hydraeuf_00000286
					     http://das.ensembl.org/das/hydraeuf_00000287
					     http://das.ensembl.org/das/hydraeuf_00000291
					     http://das.ensembl.org/das/hydraeuf_00000292
					     http://das.ensembl.org/das/hydraeuf_00000293
					     http://das.ensembl.org/das/hydraeuf_00000294
					     http://das.ensembl.org/das/hydraeuf_00000295
					     http://das.ensembl.org/das/hydraeuf_00000296
					     http://das.ensembl.org/das/hydraeuf_00000297
					       )],
#			     'callback' => $cb,
			    });

#$das->features("1:1,1000000");
#$das->features("1:1,1000000", $cb);
#$das->features([
#		"1:1,1000000",
#		"2:1,1000000",
#		],
#	       $cb);

$das->features("13:31787617,31871805",$cb);

print map { "$_\t$counts->{$_}\n" } sort keys %{$counts};
