#!/usr/bin/perl -wT
use strict;
use lib qw(lib ../lib);
use Bio::DasLite;
use Data::Dumper;
$Bio::DasLite::DEBUG = 1;

my $das              = Bio::DasLite->new();
my $sources          = $das->registry_sources();
my $count_all        = scalar @{$das->registry_sources()};
my $count_stylesheet = scalar @{$das->registry_sources({
							'capability' => ['stylesheet']
						       })};
my $count_protein    = scalar @{$das->registry_sources({
							'category'   => ['Protein Sequence']
						       })};;

print Dumper($das->registry_sources());

print STDERR qq(
all        = $count_all
stylesheet = $count_stylesheet
protein    = $count_protein
\n);
